import { UserAdminType } from "redux/apiCalls";

export const data = [
  {
    name: "January",
    connected: 4,
  },
  {
    name: "February",
    connected: 30,
  },
  {
    name: "March",
    connected: 58,
  },
  {
    name: "April",
    connected: 65,
  },
  {
    name: "Mai",
    connected: 20,
  },
  {
    name: "June",
    connected: 75,
  },
  {
    name: "July",
    connected: 65,
  },
  {
    name: "August",
    connected: 90,
  },
  {
    name: "September",
    connected: 63,
  },
  {
    name: "October",
    connected: 46,
  },
  {
    name: "November",
    connected: 97,
  },
  {
    name: "December",
    connected: 84,
  },
];

export const users: UserAdminType[] = [
  {
    _id: "1",
    username: "Snow",
    email: "Jon@gmail.com",
    isAdmin: false,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "2",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "3",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "4",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "5",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "6",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "7",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "8",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "9",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "1",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
  {
    _id: "1",
    username: "Cersei",
    email: "Cersei@gmail.com",
    isAdmin: true,
    password: "",
    isSubscribed: true,
    fullName: "Alexandre Malet",
  },
];

export const products = [
  {
    id: 1,
    name: "Apple Macbook Pro",
    stock: 500,
    status: "active",
    price: "540$",
    img: "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg",
  },
  {
    id: 2,
    name: "Apple Macbook Air",
    stock: 680,
    status: "active",
    price: "350$",
    img: "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg",
  },
  {
    id: 3,
    name: "Apple Ipad Pro",
    stock: 6320,
    status: "active",
    price: "780$",
    img: "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg",
  },
  {
    id: 4,
    name: "Apple Ipad Air",
    stock: 230,
    status: "active",
    price: "950$",
    img: "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg",
  },
  {
    id: 2,
    name: "Apple Iphone 13 Pro max",
    stock: 890,
    status: "active",
    price: "1050$",
    img: "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg",
  },
];
